/-
Copyright (c) 2026 Erdős 617 verification project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erdős 617 verification project
-/
module

public import Erdos617.Sat.SpecialBrooksCoverage

/-!
# Generated zero-anchor orbit certificates for E043

Generated by `repro/generate_e058_zero_anchor_orbit_certificate.py`.
The three theorems exhaust at most 64 Boolean masks each.
-/

@[expose] public section

open Finset Fintype
open scoped BigOperators

namespace Erdos617

def r5ZeroAnchorP04ColumnMap
    (witness : Fin 8) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![0, 1, 2, 3]
  | 2 => ![0, 1, 3, 2]
  | 3 => ![0, 1, 3, 2]
  | 4 => ![1, 0, 2, 3]
  | 5 => ![1, 0, 2, 3]
  | 6 => ![1, 0, 3, 2]
  | 7 => ![1, 0, 3, 2]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP04ColumnInverseMap
    (witness : Fin 8) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![0, 1, 2, 3]
  | 2 => ![0, 1, 3, 2]
  | 3 => ![0, 1, 3, 2]
  | 4 => ![1, 0, 2, 3]
  | 5 => ![1, 0, 2, 3]
  | 6 => ![1, 0, 3, 2]
  | 7 => ![1, 0, 3, 2]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP04ColumnPermutation
    (witness : Fin 8) : Equiv.Perm (Fin 4) :=
  {
    toFun := r5ZeroAnchorP04ColumnMap witness
    invFun := r5ZeroAnchorP04ColumnInverseMap witness
    left_inv := by
      intro column
      fin_cases witness <;> fin_cases column <;> decide
    right_inv := by
      intro column
      fin_cases witness <;> fin_cases column <;> decide
  }

def r5ZeroAnchorP04RowMap
    (witness : Fin 8) : Fin 6 → Fin 6 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3, 4, 5]
  | 1 => ![1, 0, 2, 3, 4, 5]
  | 2 => ![0, 1, 3, 2, 4, 5]
  | 3 => ![1, 0, 3, 2, 4, 5]
  | 4 => ![0, 1, 2, 3, 5, 4]
  | 5 => ![1, 0, 2, 3, 5, 4]
  | 6 => ![0, 1, 3, 2, 5, 4]
  | 7 => ![1, 0, 3, 2, 5, 4]
  | _ => ![0, 1, 2, 3, 4, 5]

def r5ZeroAnchorP04RowInverseMap
    (witness : Fin 8) : Fin 6 → Fin 6 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3, 4, 5]
  | 1 => ![1, 0, 2, 3, 4, 5]
  | 2 => ![0, 1, 3, 2, 4, 5]
  | 3 => ![1, 0, 3, 2, 4, 5]
  | 4 => ![0, 1, 2, 3, 5, 4]
  | 5 => ![1, 0, 2, 3, 5, 4]
  | 6 => ![0, 1, 3, 2, 5, 4]
  | 7 => ![1, 0, 3, 2, 5, 4]
  | _ => ![0, 1, 2, 3, 4, 5]

def r5ZeroAnchorP04RowPermutation
    (witness : Fin 8) : Equiv.Perm (Fin 6) :=
  {
    toFun := r5ZeroAnchorP04RowMap witness
    invFun := r5ZeroAnchorP04RowInverseMap witness
    left_inv := by
      intro row
      fin_cases witness <;> fin_cases row <;> decide
    right_inv := by
      intro row
      fin_cases witness <;> fin_cases row <;> decide
  }

def r5ZeroAnchorP04ActionMap
    (witness : Fin 8) (vertex : Fin 26) : Fin 26 :=
  if hcolumn :
      1 ≤ (vertex : Nat) ∧ (vertex : Nat) < 5 then
    ⟨(r5ZeroAnchorP04ColumnInverseMap witness
        ⟨(vertex : Nat) - 1, by omega⟩ : Nat) + 1,
      by omega⟩
  else if hrow : 20 ≤ (vertex : Nat) then
    ⟨(r5ZeroAnchorP04RowInverseMap witness
        ⟨(vertex : Nat) - 20, by omega⟩ : Nat) +
        20,
      by omega⟩
  else
    vertex

def r5ZeroAnchorP04ActionInverseMap
    (witness : Fin 8) (vertex : Fin 26) : Fin 26 :=
  if hcolumn :
      1 ≤ (vertex : Nat) ∧ (vertex : Nat) < 5 then
    ⟨(r5ZeroAnchorP04ColumnMap witness
        ⟨(vertex : Nat) - 1, by omega⟩ : Nat) + 1,
      by omega⟩
  else if hrow : 20 ≤ (vertex : Nat) then
    ⟨(r5ZeroAnchorP04RowMap witness
        ⟨(vertex : Nat) - 20, by omega⟩ : Nat) +
        20,
      by omega⟩
  else
    vertex

def r5ZeroAnchorP04ActionRelabeling
    (witness : Fin 8) : Equiv.Perm (Fin 26) :=
  {
    toFun := r5ZeroAnchorP04ActionMap witness
    invFun := r5ZeroAnchorP04ActionInverseMap witness
    left_inv := by
      intro vertex
      fin_cases witness <;> fin_cases vertex <;> decide
    right_inv := by
      intro vertex
      fin_cases witness <;> fin_cases vertex <;> decide
  }

def r5ZeroAnchorP04Pattern : Fin 6 → Nat :=
  ![1, 1, 3, 5, 8, 16]

def r5ZeroAnchorP04TransformedPattern
    (row : Fin 6) (witness : Fin 8) : Nat :=
  (∑ column : Fin 4,
    edgeBit
        (Nat.testBit (r5ZeroAnchorP04Pattern row)
          (4 - (column : Nat))) *
      2 ^ (4 -
        (r5ZeroAnchorP04ColumnMap witness column : Nat))) +
    edgeBit (Nat.testBit (r5ZeroAnchorP04Pattern row) 0)

theorem r5ZeroAnchorP04Pattern_stabilizer :
    ∀ witness row,
      r5ZeroAnchorP04TransformedPattern row witness =
        r5ZeroAnchorP04Pattern
          (r5ZeroAnchorP04RowMap witness row) := by
  decide

def r5ZeroAnchorP04Representative : Fin 26 → Nat :=
  ![0, 1, 3, 4, 5, 7, 12, 13, 15, 16, 17, 19,
    20, 21, 23, 28, 29, 31, 48, 49, 51, 52, 53, 55,
    60, 61]

def r5ZeroAnchorP04RepresentativeWeight
    (child : Fin 26) : Nat :=
  ∑ index : Fin 6,
    edgeBit
      (Nat.testBit (r5ZeroAnchorP04Representative child)
        (index : Nat))

theorem r5ZeroAnchorP04RepresentativeWeight_le_five :
    ∀ child, r5ZeroAnchorP04RepresentativeWeight child ≤ 5 := by
  decide

def r5ZeroAnchorP04Mask (bits : Fin 6 → Bool) : Nat :=
  ∑ index, edgeBit (bits index) * 2 ^ (index : Nat)

def r5ZeroAnchorP04TransformedMask
    (bits : Fin 6 → Bool) (witness : Fin 8) : Nat :=
  ∑ index, edgeBit (bits index) *
    2 ^ (r5ZeroAnchorP04RowMap witness index : Nat)

def r5ZeroAnchorP04TransformedBits
    (bits : Fin 6 → Bool) (witness : Fin 8) :
    Fin 6 → Bool :=
  fun index =>
    bits (r5ZeroAnchorP04RowInverseMap witness index)

theorem r5ZeroAnchorP04Mask_lt :
    ∀ bits : Fin 6 → Bool,
      r5ZeroAnchorP04Mask bits < 2 ^ 6 := by
  decide

def r5ZeroAnchorP04WitnessChild
    (bits : Fin 6 → Bool) : Fin 26 :=
  (![0, 1, 1, 2, 3, 4, 4, 5, 3, 4, 4, 5,
    6, 7, 7, 8, 9, 10, 10, 11, 12, 13, 13, 14,
    12, 13, 13, 14, 15, 16, 16, 17, 9, 10, 10, 11,
    12, 13, 13, 14, 12, 13, 13, 14, 15, 16, 16, 17,
    18, 19, 19, 20, 21, 22, 22, 23, 21, 22, 22, 23,
    24, 25, 25, 0])
    ⟨r5ZeroAnchorP04Mask bits,
      r5ZeroAnchorP04Mask_lt bits⟩

def r5ZeroAnchorP04WitnessAction
    (bits : Fin 6 → Bool) : Fin 8 :=
  (![0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 3, 2,
    0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
    2, 2, 3, 2, 0, 0, 1, 0, 4, 4, 5, 4,
    4, 4, 5, 4, 6, 6, 7, 6, 4, 4, 5, 4,
    0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 3, 2,
    0, 0, 1, 0])
    ⟨r5ZeroAnchorP04Mask bits,
      r5ZeroAnchorP04Mask_lt bits⟩

set_option maxRecDepth 10000 in
theorem r5_zero_anchor_04_orbit_check :
    ∀ bits : Fin 6 → Bool,
      (∑ index, edgeBit (bits index)) ≤ 5 →
      r5ZeroAnchorP04TransformedMask bits
          (r5ZeroAnchorP04WitnessAction bits) =
      r5ZeroAnchorP04Representative
          (r5ZeroAnchorP04WitnessChild bits) := by
  decide

set_option maxRecDepth 10000 in
theorem r5_zero_anchor_04_orbit_bits_check :
    ∀ bits : Fin 6 → Bool,
      (∑ index, edgeBit (bits index)) ≤ 5 →
      ∀ index,
        r5ZeroAnchorP04TransformedBits bits
            (r5ZeroAnchorP04WitnessAction bits) index =
          Nat.testBit
            (r5ZeroAnchorP04Representative
              (r5ZeroAnchorP04WitnessChild bits))
            (index : Nat) := by
  decide


def r5ZeroAnchorP09ColumnMap
    (witness : Fin 6) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![0, 1, 3, 2]
  | 2 => ![0, 2, 1, 3]
  | 3 => ![0, 2, 3, 1]
  | 4 => ![0, 3, 1, 2]
  | 5 => ![0, 3, 2, 1]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP09ColumnInverseMap
    (witness : Fin 6) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![0, 1, 3, 2]
  | 2 => ![0, 2, 1, 3]
  | 3 => ![0, 3, 1, 2]
  | 4 => ![0, 2, 3, 1]
  | 5 => ![0, 3, 2, 1]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP09ColumnPermutation
    (witness : Fin 6) : Equiv.Perm (Fin 4) :=
  {
    toFun := r5ZeroAnchorP09ColumnMap witness
    invFun := r5ZeroAnchorP09ColumnInverseMap witness
    left_inv := by
      intro column
      fin_cases witness <;> fin_cases column <;> decide
    right_inv := by
      intro column
      fin_cases witness <;> fin_cases column <;> decide
  }

def r5ZeroAnchorP09RowMap
    (witness : Fin 6) : Fin 5 → Fin 5 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3, 4]
  | 1 => ![0, 2, 1, 3, 4]
  | 2 => ![0, 1, 3, 2, 4]
  | 3 => ![0, 3, 1, 2, 4]
  | 4 => ![0, 2, 3, 1, 4]
  | 5 => ![0, 3, 2, 1, 4]
  | _ => ![0, 1, 2, 3, 4]

def r5ZeroAnchorP09RowInverseMap
    (witness : Fin 6) : Fin 5 → Fin 5 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3, 4]
  | 1 => ![0, 2, 1, 3, 4]
  | 2 => ![0, 1, 3, 2, 4]
  | 3 => ![0, 2, 3, 1, 4]
  | 4 => ![0, 3, 1, 2, 4]
  | 5 => ![0, 3, 2, 1, 4]
  | _ => ![0, 1, 2, 3, 4]

def r5ZeroAnchorP09RowPermutation
    (witness : Fin 6) : Equiv.Perm (Fin 5) :=
  {
    toFun := r5ZeroAnchorP09RowMap witness
    invFun := r5ZeroAnchorP09RowInverseMap witness
    left_inv := by
      intro row
      fin_cases witness <;> fin_cases row <;> decide
    right_inv := by
      intro row
      fin_cases witness <;> fin_cases row <;> decide
  }

def r5ZeroAnchorP09ActionMap
    (witness : Fin 6) (vertex : Fin 26) : Fin 26 :=
  if hcolumn :
      1 ≤ (vertex : Nat) ∧ (vertex : Nat) < 5 then
    ⟨(r5ZeroAnchorP09ColumnInverseMap witness
        ⟨(vertex : Nat) - 1, by omega⟩ : Nat) + 1,
      by omega⟩
  else if hrow : 21 ≤ (vertex : Nat) then
    ⟨(r5ZeroAnchorP09RowInverseMap witness
        ⟨(vertex : Nat) - 21, by omega⟩ : Nat) +
        21,
      by omega⟩
  else
    vertex

def r5ZeroAnchorP09ActionInverseMap
    (witness : Fin 6) (vertex : Fin 26) : Fin 26 :=
  if hcolumn :
      1 ≤ (vertex : Nat) ∧ (vertex : Nat) < 5 then
    ⟨(r5ZeroAnchorP09ColumnMap witness
        ⟨(vertex : Nat) - 1, by omega⟩ : Nat) + 1,
      by omega⟩
  else if hrow : 21 ≤ (vertex : Nat) then
    ⟨(r5ZeroAnchorP09RowMap witness
        ⟨(vertex : Nat) - 21, by omega⟩ : Nat) +
        21,
      by omega⟩
  else
    vertex

def r5ZeroAnchorP09ActionRelabeling
    (witness : Fin 6) : Equiv.Perm (Fin 26) :=
  {
    toFun := r5ZeroAnchorP09ActionMap witness
    invFun := r5ZeroAnchorP09ActionInverseMap witness
    left_inv := by
      intro vertex
      fin_cases witness <;> fin_cases vertex <;> decide
    right_inv := by
      intro vertex
      fin_cases witness <;> fin_cases vertex <;> decide
  }

def r5ZeroAnchorP09Pattern : Fin 5 → Nat :=
  ![1, 3, 5, 9, 16]

def r5ZeroAnchorP09TransformedPattern
    (row : Fin 5) (witness : Fin 6) : Nat :=
  (∑ column : Fin 4,
    edgeBit
        (Nat.testBit (r5ZeroAnchorP09Pattern row)
          (4 - (column : Nat))) *
      2 ^ (4 -
        (r5ZeroAnchorP09ColumnMap witness column : Nat))) +
    edgeBit (Nat.testBit (r5ZeroAnchorP09Pattern row) 0)

theorem r5ZeroAnchorP09Pattern_stabilizer :
    ∀ witness row,
      r5ZeroAnchorP09TransformedPattern row witness =
        r5ZeroAnchorP09Pattern
          (r5ZeroAnchorP09RowMap witness row) := by
  decide

def r5ZeroAnchorP09Representative : Fin 16 → Nat :=
  ![0, 1, 2, 3, 6, 7, 14, 15, 16, 17, 18, 19,
    22, 23, 30, 31]

def r5ZeroAnchorP09RepresentativeWeight
    (child : Fin 16) : Nat :=
  ∑ index : Fin 5,
    edgeBit
      (Nat.testBit (r5ZeroAnchorP09Representative child)
        (index : Nat))

theorem r5ZeroAnchorP09RepresentativeWeight_le_five :
    ∀ child, r5ZeroAnchorP09RepresentativeWeight child ≤ 5 := by
  decide

def r5ZeroAnchorP09Mask (bits : Fin 5 → Bool) : Nat :=
  ∑ index, edgeBit (bits index) * 2 ^ (index : Nat)

def r5ZeroAnchorP09TransformedMask
    (bits : Fin 5 → Bool) (witness : Fin 6) : Nat :=
  ∑ index, edgeBit (bits index) *
    2 ^ (r5ZeroAnchorP09RowMap witness index : Nat)

def r5ZeroAnchorP09TransformedBits
    (bits : Fin 5 → Bool) (witness : Fin 6) :
    Fin 5 → Bool :=
  fun index =>
    bits (r5ZeroAnchorP09RowInverseMap witness index)

theorem r5ZeroAnchorP09Mask_lt :
    ∀ bits : Fin 5 → Bool,
      r5ZeroAnchorP09Mask bits < 2 ^ 5 := by
  decide

def r5ZeroAnchorP09WitnessChild
    (bits : Fin 5 → Bool) : Fin 16 :=
  (![0, 1, 2, 3, 2, 3, 4, 5, 2, 3, 4, 5,
    4, 5, 6, 7, 8, 9, 10, 11, 10, 11, 12, 13,
    10, 11, 12, 13, 12, 13, 14, 15])
    ⟨r5ZeroAnchorP09Mask bits,
      r5ZeroAnchorP09Mask_lt bits⟩

def r5ZeroAnchorP09WitnessAction
    (bits : Fin 5 → Bool) : Fin 6 :=
  (![0, 0, 0, 0, 1, 1, 0, 0, 4, 4, 2, 2,
    3, 3, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
    4, 4, 2, 2, 3, 3, 0, 0])
    ⟨r5ZeroAnchorP09Mask bits,
      r5ZeroAnchorP09Mask_lt bits⟩

set_option maxRecDepth 10000 in
theorem r5_zero_anchor_09_orbit_check :
    ∀ bits : Fin 5 → Bool,
      (∑ index, edgeBit (bits index)) ≤ 5 →
      r5ZeroAnchorP09TransformedMask bits
          (r5ZeroAnchorP09WitnessAction bits) =
      r5ZeroAnchorP09Representative
          (r5ZeroAnchorP09WitnessChild bits) := by
  decide

set_option maxRecDepth 10000 in
theorem r5_zero_anchor_09_orbit_bits_check :
    ∀ bits : Fin 5 → Bool,
      (∑ index, edgeBit (bits index)) ≤ 5 →
      ∀ index,
        r5ZeroAnchorP09TransformedBits bits
            (r5ZeroAnchorP09WitnessAction bits) index =
          Nat.testBit
            (r5ZeroAnchorP09Representative
              (r5ZeroAnchorP09WitnessChild bits))
            (index : Nat) := by
  decide


def r5ZeroAnchorP19ColumnMap
    (witness : Fin 24) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![0, 1, 3, 2]
  | 2 => ![0, 2, 1, 3]
  | 3 => ![0, 2, 3, 1]
  | 4 => ![0, 3, 1, 2]
  | 5 => ![0, 3, 2, 1]
  | 6 => ![1, 0, 2, 3]
  | 7 => ![1, 0, 3, 2]
  | 8 => ![1, 2, 0, 3]
  | 9 => ![1, 2, 3, 0]
  | 10 => ![1, 3, 0, 2]
  | 11 => ![1, 3, 2, 0]
  | 12 => ![2, 0, 1, 3]
  | 13 => ![2, 0, 3, 1]
  | 14 => ![2, 1, 0, 3]
  | 15 => ![2, 1, 3, 0]
  | 16 => ![2, 3, 0, 1]
  | 17 => ![2, 3, 1, 0]
  | 18 => ![3, 0, 1, 2]
  | 19 => ![3, 0, 2, 1]
  | 20 => ![3, 1, 0, 2]
  | 21 => ![3, 1, 2, 0]
  | 22 => ![3, 2, 0, 1]
  | 23 => ![3, 2, 1, 0]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP19ColumnInverseMap
    (witness : Fin 24) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![0, 1, 3, 2]
  | 2 => ![0, 2, 1, 3]
  | 3 => ![0, 3, 1, 2]
  | 4 => ![0, 2, 3, 1]
  | 5 => ![0, 3, 2, 1]
  | 6 => ![1, 0, 2, 3]
  | 7 => ![1, 0, 3, 2]
  | 8 => ![2, 0, 1, 3]
  | 9 => ![3, 0, 1, 2]
  | 10 => ![2, 0, 3, 1]
  | 11 => ![3, 0, 2, 1]
  | 12 => ![1, 2, 0, 3]
  | 13 => ![1, 3, 0, 2]
  | 14 => ![2, 1, 0, 3]
  | 15 => ![3, 1, 0, 2]
  | 16 => ![2, 3, 0, 1]
  | 17 => ![3, 2, 0, 1]
  | 18 => ![1, 2, 3, 0]
  | 19 => ![1, 3, 2, 0]
  | 20 => ![2, 1, 3, 0]
  | 21 => ![3, 1, 2, 0]
  | 22 => ![2, 3, 1, 0]
  | 23 => ![3, 2, 1, 0]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP19ColumnPermutation
    (witness : Fin 24) : Equiv.Perm (Fin 4) :=
  {
    toFun := r5ZeroAnchorP19ColumnMap witness
    invFun := r5ZeroAnchorP19ColumnInverseMap witness
    left_inv := by
      intro column
      fin_cases witness <;> fin_cases column <;> decide
    right_inv := by
      intro column
      fin_cases witness <;> fin_cases column <;> decide
  }

def r5ZeroAnchorP19RowMap
    (witness : Fin 24) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![1, 0, 2, 3]
  | 2 => ![0, 2, 1, 3]
  | 3 => ![2, 0, 1, 3]
  | 4 => ![1, 2, 0, 3]
  | 5 => ![2, 1, 0, 3]
  | 6 => ![0, 1, 3, 2]
  | 7 => ![1, 0, 3, 2]
  | 8 => ![0, 3, 1, 2]
  | 9 => ![3, 0, 1, 2]
  | 10 => ![1, 3, 0, 2]
  | 11 => ![3, 1, 0, 2]
  | 12 => ![0, 2, 3, 1]
  | 13 => ![2, 0, 3, 1]
  | 14 => ![0, 3, 2, 1]
  | 15 => ![3, 0, 2, 1]
  | 16 => ![2, 3, 0, 1]
  | 17 => ![3, 2, 0, 1]
  | 18 => ![1, 2, 3, 0]
  | 19 => ![2, 1, 3, 0]
  | 20 => ![1, 3, 2, 0]
  | 21 => ![3, 1, 2, 0]
  | 22 => ![2, 3, 1, 0]
  | 23 => ![3, 2, 1, 0]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP19RowInverseMap
    (witness : Fin 24) : Fin 4 → Fin 4 :=
  match witness.val with
  | 0 => ![0, 1, 2, 3]
  | 1 => ![1, 0, 2, 3]
  | 2 => ![0, 2, 1, 3]
  | 3 => ![1, 2, 0, 3]
  | 4 => ![2, 0, 1, 3]
  | 5 => ![2, 1, 0, 3]
  | 6 => ![0, 1, 3, 2]
  | 7 => ![1, 0, 3, 2]
  | 8 => ![0, 2, 3, 1]
  | 9 => ![1, 2, 3, 0]
  | 10 => ![2, 0, 3, 1]
  | 11 => ![2, 1, 3, 0]
  | 12 => ![0, 3, 1, 2]
  | 13 => ![1, 3, 0, 2]
  | 14 => ![0, 3, 2, 1]
  | 15 => ![1, 3, 2, 0]
  | 16 => ![2, 3, 0, 1]
  | 17 => ![2, 3, 1, 0]
  | 18 => ![3, 0, 1, 2]
  | 19 => ![3, 1, 0, 2]
  | 20 => ![3, 0, 2, 1]
  | 21 => ![3, 1, 2, 0]
  | 22 => ![3, 2, 0, 1]
  | 23 => ![3, 2, 1, 0]
  | _ => ![0, 1, 2, 3]

def r5ZeroAnchorP19RowPermutation
    (witness : Fin 24) : Equiv.Perm (Fin 4) :=
  {
    toFun := r5ZeroAnchorP19RowMap witness
    invFun := r5ZeroAnchorP19RowInverseMap witness
    left_inv := by
      intro row
      fin_cases witness <;> fin_cases row <;> decide
    right_inv := by
      intro row
      fin_cases witness <;> fin_cases row <;> decide
  }

def r5ZeroAnchorP19ActionMap
    (witness : Fin 24) (vertex : Fin 26) : Fin 26 :=
  if hcolumn :
      1 ≤ (vertex : Nat) ∧ (vertex : Nat) < 5 then
    ⟨(r5ZeroAnchorP19ColumnInverseMap witness
        ⟨(vertex : Nat) - 1, by omega⟩ : Nat) + 1,
      by omega⟩
  else if hrow : 22 ≤ (vertex : Nat) then
    ⟨(r5ZeroAnchorP19RowInverseMap witness
        ⟨(vertex : Nat) - 22, by omega⟩ : Nat) +
        22,
      by omega⟩
  else
    vertex

def r5ZeroAnchorP19ActionInverseMap
    (witness : Fin 24) (vertex : Fin 26) : Fin 26 :=
  if hcolumn :
      1 ≤ (vertex : Nat) ∧ (vertex : Nat) < 5 then
    ⟨(r5ZeroAnchorP19ColumnMap witness
        ⟨(vertex : Nat) - 1, by omega⟩ : Nat) + 1,
      by omega⟩
  else if hrow : 22 ≤ (vertex : Nat) then
    ⟨(r5ZeroAnchorP19RowMap witness
        ⟨(vertex : Nat) - 22, by omega⟩ : Nat) +
        22,
      by omega⟩
  else
    vertex

def r5ZeroAnchorP19ActionRelabeling
    (witness : Fin 24) : Equiv.Perm (Fin 26) :=
  {
    toFun := r5ZeroAnchorP19ActionMap witness
    invFun := r5ZeroAnchorP19ActionInverseMap witness
    left_inv := by
      intro vertex
      fin_cases witness <;> fin_cases vertex <;> decide
    right_inv := by
      intro vertex
      fin_cases witness <;> fin_cases vertex <;> decide
  }

def r5ZeroAnchorP19Pattern : Fin 4 → Nat :=
  ![3, 5, 9, 17]

def r5ZeroAnchorP19TransformedPattern
    (row : Fin 4) (witness : Fin 24) : Nat :=
  (∑ column : Fin 4,
    edgeBit
        (Nat.testBit (r5ZeroAnchorP19Pattern row)
          (4 - (column : Nat))) *
      2 ^ (4 -
        (r5ZeroAnchorP19ColumnMap witness column : Nat))) +
    edgeBit (Nat.testBit (r5ZeroAnchorP19Pattern row) 0)

theorem r5ZeroAnchorP19Pattern_stabilizer :
    ∀ witness row,
      r5ZeroAnchorP19TransformedPattern row witness =
        r5ZeroAnchorP19Pattern
          (r5ZeroAnchorP19RowMap witness row) := by
  decide

def r5ZeroAnchorP19Representative : Fin 5 → Nat :=
  ![0, 1, 3, 7, 15]

def r5ZeroAnchorP19RepresentativeWeight
    (child : Fin 5) : Nat :=
  ∑ index : Fin 4,
    edgeBit
      (Nat.testBit (r5ZeroAnchorP19Representative child)
        (index : Nat))

theorem r5ZeroAnchorP19RepresentativeWeight_le_five :
    ∀ child, r5ZeroAnchorP19RepresentativeWeight child ≤ 5 := by
  decide

def r5ZeroAnchorP19Mask (bits : Fin 4 → Bool) : Nat :=
  ∑ index, edgeBit (bits index) * 2 ^ (index : Nat)

def r5ZeroAnchorP19TransformedMask
    (bits : Fin 4 → Bool) (witness : Fin 24) : Nat :=
  ∑ index, edgeBit (bits index) *
    2 ^ (r5ZeroAnchorP19RowMap witness index : Nat)

def r5ZeroAnchorP19TransformedBits
    (bits : Fin 4 → Bool) (witness : Fin 24) :
    Fin 4 → Bool :=
  fun index =>
    bits (r5ZeroAnchorP19RowInverseMap witness index)

theorem r5ZeroAnchorP19Mask_lt :
    ∀ bits : Fin 4 → Bool,
      r5ZeroAnchorP19Mask bits < 2 ^ 4 := by
  decide

def r5ZeroAnchorP19WitnessChild
    (bits : Fin 4 → Bool) : Fin 5 :=
  (![0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3,
    2, 3, 3, 4])
    ⟨r5ZeroAnchorP19Mask bits,
      r5ZeroAnchorP19Mask_lt bits⟩

def r5ZeroAnchorP19WitnessAction
    (bits : Fin 4 → Bool) : Fin 24 :=
  (![0, 0, 1, 0, 4, 2, 3, 0, 18, 12, 13, 6,
    16, 8, 9, 0])
    ⟨r5ZeroAnchorP19Mask bits,
      r5ZeroAnchorP19Mask_lt bits⟩

set_option maxRecDepth 10000 in
theorem r5_zero_anchor_19_orbit_check :
    ∀ bits : Fin 4 → Bool,
      (∑ index, edgeBit (bits index)) ≤ 5 →
      r5ZeroAnchorP19TransformedMask bits
          (r5ZeroAnchorP19WitnessAction bits) =
      r5ZeroAnchorP19Representative
          (r5ZeroAnchorP19WitnessChild bits) := by
  decide

set_option maxRecDepth 10000 in
theorem r5_zero_anchor_19_orbit_bits_check :
    ∀ bits : Fin 4 → Bool,
      (∑ index, edgeBit (bits index)) ≤ 5 →
      ∀ index,
        r5ZeroAnchorP19TransformedBits bits
            (r5ZeroAnchorP19WitnessAction bits) index =
          Nat.testBit
            (r5ZeroAnchorP19Representative
              (r5ZeroAnchorP19WitnessChild bits))
            (index : Nat) := by
  decide

end Erdos617
