#!/usr/bin/env python3
"""Collect the small, reviewable evidence from a completed E058 audit.

Reduced CNFs/LRATs, staged proof fragments, and `.olean` files are deliberately
not copied: they are large derived products regenerated by the archived
scripts. Their hashes remain recorded in the copied receipts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path


def sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json(path: Path, value: object) -> None:
    path.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
        newline="\n",
    )


def selected_work_files(work: Path) -> set[Path]:
    selected = {
        work / "fresh-audit-receipt.json",
        work / "E058FreshAxiomAudit.lean",
        work / "E058FreshAxiomAudit.out",
        work / "unit_manifest.json",
        work / "cores/receipt.json",
        work / "kernel/kernel-aggregate-receipt.json",
        work / "semantic/semantic-aggregate-receipt.json",
    }
    selected.update((work / "regenerated-certificates").glob("*.lean"))
    selected.update((work / "cores").glob("*.receipt.json"))
    selected.update((work / "kernel").glob("*/kernel-receipt.json"))
    selected.update((work / "kernel").glob("*/stages/receipt.json"))
    selected.update((work / "kernel").glob("*/logs/*.log"))
    selected.update((work / "semantic").glob("*/semantic-receipt.json"))
    selected.update((work / "semantic").glob("*/logs/*.log"))
    return selected


def generated_source_inventory(lean_root: Path) -> dict[str, object]:
    paths = sorted(
        [
            *(lean_root / "generated/e058_fresh_kernel").rglob("*.lean"),
            *(lean_root / "generated/e058_fresh_semantic").rglob("*.lean"),
        ]
    )
    digest = hashlib.sha256()
    records = []
    for path in paths:
        relative = path.relative_to(lean_root)
        value = sha256_path(path)
        digest.update(str(relative).encode("utf-8"))
        digest.update(b"\0")
        digest.update(value.encode("ascii"))
        digest.update(b"\n")
        records.append(
            {
                "path": str(relative),
                "bytes": path.stat().st_size,
                "sha256": value,
            }
        )
    return {
        "count": len(records),
        "combined_sha256": digest.hexdigest(),
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fresh-repository", type=Path, required=True)
    parser.add_argument("--output-directory", type=Path, required=True)
    parser.add_argument("--executed-runner", type=Path, required=True)
    args = parser.parse_args()

    repository = args.fresh_repository.resolve()
    lean_root = repository / "formal/lean"
    work = lean_root / ".e058-audit"
    output = args.output_directory.resolve()
    output.mkdir(parents=True, exist_ok=True)
    if any(output.iterdir()):
        raise FileExistsError(f"evidence output directory is not empty: {output}")

    required = selected_work_files(work)
    missing = sorted(str(path) for path in required if not path.is_file())
    if missing:
        raise FileNotFoundError(
            "completed E058 evidence is missing: " + ", ".join(missing)
        )

    sources: list[tuple[Path, Path]] = []
    for path in sorted(required):
        sources.append((path, Path("work") / path.relative_to(work)))
    for path in sorted(
        {
            *repository.glob("e058*.log"),
            *repository.glob("e058*.json"),
            *repository.glob("e058*.lean"),
            *repository.glob("failed-run-*.log"),
        }
    ):
        if path.is_file():
            sources.append((path, Path("transcripts") / path.name))
    for path in sorted(
        (lean_root / "generated/e058_fresh_kernel").glob(
            "*/lean-stage-modules-receipt.json"
        )
    ):
        sources.append(
            (
                path,
                Path("generated-receipts")
                / path.parent.name
                / path.name,
            )
        )

    executed_runner = args.executed_runner.resolve()
    if not executed_runner.is_file():
        raise FileNotFoundError(f"executed audit runner is missing: {executed_runner}")
    sources.append(
        (
            executed_runner,
            Path("runners")
            / (
                "clean-start-runner-executed-"
                f"{sha256_path(executed_runner)}.py"
            ),
        )
    )
    final_tools = (
        repository / "repro/run_e058_special_brooks_kernel_audit.py",
        repository / "repro/run_e058_branch02_benchmark.py",
        repository / "repro/run_e058_lean_kernel_imports.py",
        repository / "repro/run_e058_lean_semantic_closures.py",
        repository / "repro/validate_e058_clean_start_sequence.py",
        repository / "repro/generate_e058_lean_stage_modules.py",
        repository / "src/split_rup_lrat_stages.py",
    )
    for tool in final_tools:
        if not tool.is_file():
            raise FileNotFoundError(f"final audit tool is missing: {tool}")
        sources.append(
            (
                tool,
                Path("runners")
                / f"final-{tool.stem}-{sha256_path(tool)}{tool.suffix}",
            )
        )

    records = []
    for source, relative in sorted(sources, key=lambda pair: str(pair[1])):
        destination = output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        records.append(
            {
                "path": str(relative),
                "bytes": destination.stat().st_size,
                "sha256": sha256_path(destination),
            }
        )

    generated_sources = generated_source_inventory(lean_root)
    final_audit = json.loads(
        (work / "fresh-audit-receipt.json").read_text(encoding="ascii")
    )
    expected_generated = final_audit.get("generated_source_inventory", {})
    if (
        generated_sources["count"] != expected_generated.get("count")
        or generated_sources["combined_sha256"]
        != expected_generated.get("combined_sha256")
    ):
        raise ValueError(
            "generated Lean source inventory differs from the final audit receipt"
        )

    receipt = {
        "schema_version": 1,
        "experiment": "E058-R5-SPECIAL-BROOKS-KERNEL-BRIDGE",
        "scope": "Small receipts, logs, audit source/output, and transcripts",
        "copied_files": len(records),
        "copied_bytes": sum(record["bytes"] for record in records),
        "records": records,
        "generated_lean_sources": generated_sources,
        "excluded_regenerable_products": [
            "formal/lean/.e058-audit/cores/*.cnf",
            "formal/lean/.e058-audit/cores/*.lrat",
            "formal/lean/.e058-audit/cores/*.map.json",
            "formal/lean/.e058-audit/kernel/*/stages/*.lrat",
            "formal/lean/.lake/build/**/*.olean",
        ],
    }
    receipt_path = output / "collection-receipt.json"
    write_json(receipt_path, receipt)
    print(
        "E058-EVIDENCE-COLLECTION-PASS "
        f"files={len(records)} bytes={receipt['copied_bytes']} "
        f"receipt_sha256={sha256_path(receipt_path)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
