#!/usr/bin/env python3
"""Generate the transparent Lean witness table for the 26 E058 orbits.

The table covers every labelled graph on the five fixed neighbors.  For each
of the 1024 ten-bit masks with at most six edges, it stores the first
lexicographic vertex permutation carrying that mask to one of the 26 pinned
canonical representatives.  Masks with more than six edges get an irrelevant
identity witness because the admissibility premise excludes them.

Lean independently checks every stored permutation for bijectivity and every
orbit equation with kernel reduction; the Python computation is therefore a
reproducible witness generator, not a trusted proof step.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
from collections import Counter
from pathlib import Path

EDGES = tuple(itertools.combinations(range(5), 2))
CATALOG = (
    0,
    1,
    3,
    7,
    15,
    19,
    20,
    21,
    23,
    28,
    29,
    31,
    54,
    55,
    58,
    59,
    62,
    63,
    126,
    183,
    184,
    185,
    187,
    207,
    220,
    221,
)


def relabel_mask(mask: int, permutation: tuple[int, ...]) -> int:
    result = 0
    for target_index, (left, right) in enumerate(EDGES):
        source = tuple(sorted((permutation[left], permutation[right])))
        source_index = EDGES.index(source)
        if mask & (1 << source_index):
            result |= 1 << target_index
    return result


def witnesses() -> tuple[tuple[int, tuple[int, ...]], ...]:
    permutations = tuple(itertools.permutations(range(5)))
    branch_of_mask = {mask: branch for branch, mask in enumerate(CATALOG)}
    records: list[tuple[int, tuple[int, ...]]] = []
    for mask in range(1 << len(EDGES)):
        if mask.bit_count() > 6:
            records.append((0, permutations[0]))
            continue
        candidates = (
            (relabel_mask(mask, permutation), permutation)
            for permutation in permutations
        )
        canonical, permutation = min(candidates)
        branch = branch_of_mask.get(canonical)
        if branch is None:
            raise AssertionError(
                f"mask {mask}: canonical representative {canonical} is absent"
            )
        if relabel_mask(mask, permutation) != CATALOG[branch]:
            raise AssertionError(f"mask {mask}: invalid orbit witness")
        records.append((branch, permutation))
    distribution = Counter(mask.bit_count() for mask in CATALOG)
    if len(records) != 1024:
        raise AssertionError("ten-bit witness table length changed")
    if distribution != Counter({0: 1, 1: 1, 2: 2, 3: 4, 4: 6, 5: 6, 6: 6}):
        raise AssertionError("canonical representative distribution changed")
    return tuple(records)


def render_entry(mask: int, branch: int, permutation: tuple[int, ...]) -> str:
    values = ", ".join(map(str, permutation))
    return f"  | {mask} => ({branch}, ![{values}])"


def render_source(records: tuple[tuple[int, tuple[int, ...]], ...]) -> str:
    entries = "\n".join(
        render_entry(mask, branch, permutation)
        for mask, (branch, permutation) in enumerate(records)
    )
    catalog = ", ".join(map(str, CATALOG))
    return f"""/-
Copyright (c) 2026 Erdős 617 verification project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erdős 617 verification project
-/
module

public import Erdos617.Sat.SpecialBrooksCoverage

/-!
# Generated neighborhood-orbit certificate for E058

This file is generated by
`repro/generate_e058_neighborhood_orbit_certificate.py`.  The table is only
witness data: the two transparent `decide` theorems below kernel-check all
1,024 bijectivity and orbit obligations.
-/

@[expose] public section

open Finset Fintype

namespace Erdos617

set_option linter.style.longLine false

def r5FiveVertexAdjacency
    (edgeBits : Fin 10 → Bool) (left right : Fin 5) : Bool :=
  if (left = 0 ∧ right = 1) ∨ (left = 1 ∧ right = 0) then edgeBits 0
  else if (left = 0 ∧ right = 2) ∨ (left = 2 ∧ right = 0) then edgeBits 1
  else if (left = 0 ∧ right = 3) ∨ (left = 3 ∧ right = 0) then edgeBits 2
  else if (left = 0 ∧ right = 4) ∨ (left = 4 ∧ right = 0) then edgeBits 3
  else if (left = 1 ∧ right = 2) ∨ (left = 2 ∧ right = 1) then edgeBits 4
  else if (left = 1 ∧ right = 3) ∨ (left = 3 ∧ right = 1) then edgeBits 5
  else if (left = 1 ∧ right = 4) ∨ (left = 4 ∧ right = 1) then edgeBits 6
  else if (left = 2 ∧ right = 3) ∨ (left = 3 ∧ right = 2) then edgeBits 7
  else if (left = 2 ∧ right = 4) ∨ (left = 4 ∧ right = 2) then edgeBits 8
  else if (left = 3 ∧ right = 4) ∨ (left = 4 ∧ right = 3) then edgeBits 9
  else false

def r5NeighborhoodRepresentativeCode : Fin 26 → Fin (2 ^ 10) :=
  ![{catalog}]

set_option maxHeartbeats 0 in
-- The generated table has 1,024 explicit finite cases.
def r5NeighborhoodOrbitWitnessData
    (code : Fin (2 ^ 10)) : Fin 26 × (Fin 5 → Fin 5) :=
  match code.val with
{entries}
  | _ => (0, ![0, 1, 2, 3, 4])

set_option maxRecDepth 20000 in
set_option maxHeartbeats 0 in
-- Exhaustive reduction checks bijectivity for all 1,024 stored witnesses.
theorem r5NeighborhoodOrbitWitness_bijective :
    ∀ code : Fin (2 ^ 10),
      Function.Bijective (r5NeighborhoodOrbitWitnessData code).2 := by
  decide

noncomputable def r5NeighborhoodOrbitWitnessPermutation
    (code : Fin (2 ^ 10)) : Equiv.Perm (Fin 5) :=
  Equiv.ofBijective
    (r5NeighborhoodOrbitWitnessData code).2
    (r5NeighborhoodOrbitWitness_bijective code)

def r5NeighborhoodOrbitWitnessCorrect (code : Fin (2 ^ 10)) : Prop :=
  (∑ index, edgeBit (edgeVectorOfCode code index)) ≤ 6 →
    ∀ left right,
      r5FiveVertexAdjacency (edgeVectorOfCode code)
          ((r5NeighborhoodOrbitWitnessData code).2 left)
          ((r5NeighborhoodOrbitWitnessData code).2 right) =
        r5FiveVertexAdjacency
          (edgeVectorOfCode
            (r5NeighborhoodRepresentativeCode
              (r5NeighborhoodOrbitWitnessData code).1))
          left right

instance instDecidableR5NeighborhoodOrbitWitnessCorrect
    (code : Fin (2 ^ 10)) :
    Decidable (r5NeighborhoodOrbitWitnessCorrect code) := by
  unfold r5NeighborhoodOrbitWitnessCorrect
  infer_instance

set_option maxRecDepth 20000 in
set_option maxHeartbeats 0 in
-- Exhaustive reduction checks every admissible orbit equation.
theorem r5NeighborhoodOrbitWitness_correct :
    ∀ code : Fin (2 ^ 10),
      r5NeighborhoodOrbitWitnessCorrect code := by
  decide

def R5NeighborhoodOrbitProperty (edgeBits : Fin 10 → Bool) : Prop :=
  (∑ index, edgeBit (edgeBits index)) ≤ 6 →
    ∃ branch : Fin 26, ∃ permutation : Equiv.Perm (Fin 5),
      ∀ left right,
        r5FiveVertexAdjacency edgeBits
            (permutation left) (permutation right) =
          r5FiveVertexAdjacency
            (edgeVectorOfCode (r5NeighborhoodRepresentativeCode branch))
            left right

theorem r5_neighborhood_orbit_code_check
    (code : Fin (2 ^ 10)) :
    R5NeighborhoodOrbitProperty (edgeVectorOfCode code) := by
  intro hedgeCount
  let data := r5NeighborhoodOrbitWitnessData code
  let permutation := r5NeighborhoodOrbitWitnessPermutation code
  refine ⟨data.1, permutation, ?_⟩
  intro left right
  change r5FiveVertexAdjacency (edgeVectorOfCode code)
      (data.2 left) (data.2 right) =
    r5FiveVertexAdjacency
      (edgeVectorOfCode (r5NeighborhoodRepresentativeCode data.1))
      left right
  exact r5NeighborhoodOrbitWitness_correct code hedgeCount left right

theorem r5_neighborhood_orbit_check (edgeBits : Fin 10 → Bool) :
    R5NeighborhoodOrbitProperty edgeBits := by
  let digits : Fin 10 → Fin 2 :=
    fun index => boolToFinTwo (edgeBits index)
  let code : Fin (2 ^ 10) := finFunctionFinEquiv digits
  have hcheck := r5_neighborhood_orbit_code_check code
  have hdecode : edgeVectorOfCode code = edgeBits := by
    funext index
    simp [edgeVectorOfCode, code, digits]
  rw [hdecode] at hcheck
  exact hcheck

end Erdos617
"""


def sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    records = witnesses()
    source = render_source(records)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8", newline="\n")
    certified = sum(mask.bit_count() <= 6 for mask in range(1024))
    print(
        "E058-NEIGHBORHOOD-ORBIT-WITNESS-GENERATION-PASS "
        f"masks=1024 admissible_masks={certified} permutations=120 "
        f"sha256={sha256_path(args.output)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
