/-
Copyright (c) 2026 Erdős 617 verification project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erdős 617 verification project
-/
module

public import Erdos617

/-!
# Axiom audit

These commands expose the transitive logical assumptions of every exported
theorem in the current partial formalization.  The build log is retained as a
reproducibility artifact at each checkpoint.
-/

#print axioms Erdos617.problem617At_five_iff_r5Upper
#print axioms Erdos617.colorGraph_adj_iff
#print axioms Erdos617.colorAbsent_iff_isIndepSet
#print axioms Erdos617.colorAbsent_iff_isClique_compl
#print axioms Erdos617.isCounterexample_iff_indepSetFree
#print axioms Erdos617.isCounterexample_iff_compl_cliqueFree
#print axioms Erdos617.iSup_colorGraph
#print axioms Erdos617.pairwise_disjoint_colorGraph
#print axioms Erdos617.IsCounterexample.pullbackEquiv
#print axioms Erdos617.upperStatement_iff_no_counterexample
#print axioms Erdos617.r5Upper_iff_no_counterexample

#print axioms Erdos617.affineRawColor_comm
#print axioms Erdos617.affineRawColor_of_lineCoordinate_eq
#print axioms Erdos617.affineColoring_get
#print axioms Erdos617.card_affinePoint
#print axioms Erdos617.affineColoring_isCounterexample
#print axioms Erdos617.affine25Coloring_isCounterexample
#print axioms Erdos617.not_upperStatement_fin25

#print axioms Erdos617.sup_compl_colorGraph_eq_top
#print axioms Erdos617.card_le_mul_of_sup_eq_top_colorable
#print axioms Erdos617.card_le_mul_of_compl_colorGraph_colorable
#print axioms Erdos617.not_two_compl_colorGraphs_fiveColorable

#print axioms Erdos617.restrictColoring_surjective_of_seesEveryColor
#print axioms Erdos617.card_fiber_add_pred_le_of_surjective
#print axioms Erdos617.card_top_edges_of_card_six
#print axioms Erdos617.colorFiber_card_between_one_eleven
#print axioms Erdos617.mem_induced_colorGraph_edgeSet_iff
#print axioms Erdos617.card_colorFiber_eq_card_induced_colorGraph
#print axioms Erdos617.induced_colorGraph_card_between_one_eleven
#print axioms Erdos617.colorGraph_admissible_of_counterexample
#print axioms Erdos617.sum_card_fibers
#print axioms Erdos617.sum_card_colorFiber
#print axioms Erdos617.mem_colorGraph_edgeSet_iff
#print axioms Erdos617.card_colorGraph_edgeFinset_eq_card_fiber
#print axioms Erdos617.sum_card_colorGraph_edgeFinset
#print axioms Erdos617.exists_colorGraph_card_le_65

#print axioms Erdos617.card_edgeFinset_add_card_compl
#print axioms Erdos617.compl_colorGraph_cliqueFree_six
#print axioms Erdos617.compl_colorGraph_card_le_270
#print axioms Erdos617.colorGraph_card_ge_55

#print axioms Erdos617.card_edgeFinset_ge_66_of_compl_cliqueFree_six_of_isIsolated
#print axioms Erdos617.colorGraph_not_isIsolated_of_card_le_65
#print axioms Erdos617.exists_sparse_nonisolated_colorGraph

#print axioms Erdos617.neighborhoodInternalEdgeCount_eq_induce
#print axioms Erdos617.degree_neighbor_eq_one_add_internal_add_cross
#print axioms Erdos617.sum_degrees_neighborFinset_eq_accounting
#print axioms Erdos617.neighborhood_cross_add_twice_internal_ge
#print axioms Erdos617.neighborhoodInternalEdgeCount_le_choose_degree
#print axioms Erdos617.neighborhood_cross_add_internal_ge_choose_degree
#print axioms Erdos617.card_between_self_eq_card_induce
#print axioms Erdos617.degree_add_internal_le_closedNeighborhood
#print axioms Erdos617.neighborhoodInternalEdgeCount_le_six_of_admissible_degree_five
#print axioms Erdos617.neighborhood_cross_add_internal_ge_fourteen
#print axioms Erdos617.neighborhood_accounting_equality_forces_extremes
#print axioms Erdos617.neighborhood_extreme_counts_isolatedClique
#print axioms Erdos617.neighborhood_accounting_equality_isolatedClique

#print axioms Erdos617.compl_degree_le_five_of_admissible_indepSetFree_three
#print axioms Erdos617.card_induce_insert_eq_between_degree_of_independent
#print axioms Erdos617.induce_compl_eq_compl_induce
#print axioms Erdos617.four_le_card_induced_compl_of_admissible_six
#print axioms Erdos617.compl_degree_le_four_of_admissible_indepSetFree_three
#print axioms Erdos617.choose_card_le_edges_add_twice_card_of_admissible_indepSetFree_three

#print axioms Erdos617.card_edgeFinset_eq_induce_add_between_add_induce_compl
#print axioms Erdos617.admissible_induce
#print axioms Erdos617.between_closedNeighborhood_exterior_eq_between_neighbor_exterior
#print axioms Erdos617.exterior_edges_add_degree_add_accounting_le_edges
#print axioms Erdos617.indepSetFree_exterior_induce
#print axioms Erdos617.exists_minimal_vertex_card_mul_degree_le_twice_edges
#print axioms Erdos617.card_exteriorFinset
#print axioms Erdos617.card_exterior_type_add_degree_add_one
#print axioms Erdos617.exterior_edges_add_degree_add_choose_le_edges
#print axioms Erdos617.exterior_edges_add_nineteen_le_edges_of_admissible_degree_five
#print axioms Erdos617.card_edges_ge_of_admissible_indepSetFree_four
#print axioms Erdos617.card_edges_ge_fiftyFour_of_admissible_indepSetFree_four_card_eighteen
#print axioms Erdos617.card_edges_ge_fiftySix_of_admissible_indepSetFree_four_card_nineteen
#print axioms Erdos617.card_edges_ge_sixtyTwo_of_admissible_indepSetFree_four_card_twenty
#print axioms Erdos617.card_edges_ge_sixtyNine_of_admissible_indepSetFree_four_card_twentyOne
#print axioms Erdos617.card_edges_ge_seventySix_of_admissible_indepSetFree_four_card_twentyTwo
#print axioms Erdos617.card_edges_ge_eightyThree_of_admissible_indepSetFree_four_card_twentyThree
#print axioms Erdos617.card_edges_ge_ninety_of_admissible_indepSetFree_four_card_twentyFour
#print axioms Erdos617.card_edges_ge_sixtyFive_of_admissible_indepSetFree_five_card_twentyFour
#print axioms Erdos617.card_edges_ge_seventyOne_of_admissible_indepSetFree_five_card_twentyFive

#print axioms Erdos617.six_cross_values_eq_two
#print axioms Erdos617.eq_sdiff_of_subset_card_two_disjoint
#print axioms Erdos617.exists_equal_label_pair_and_third
#print axioms Erdos617.labels_not_injective_of_six_vertices_four_edges
#print axioms Erdos617.card_induce_pair_add_between_degrees_of_independent
#print axioms Erdos617.degree_eq_between_neighbor_exterior_add_induce_exterior
#print axioms Erdos617.card_induce_closedNeighborhood_eq_degree_of_triangleFree
#print axioms Erdos617.card_induce_union_eq_between_add_induce_of_independent
#print axioms Erdos617.card_induce_eq_zero_of_independent
#print axioms Erdos617.compl_degree_le_four_of_admissible_indepSetFree_three_card_eleven
#print axioms Erdos617.exterior_cross_degree_eq_two_of_admissible_order_eleven
#print axioms Erdos617.four_le_card_exterior_edges_of_admissible_order_eleven
#print axioms Erdos617.exists_exterior_equal_label_pair_and_third_of_order_eleven
#print axioms Erdos617.degree_four_compl_impossible_of_twenty_edges_order_eleven
#print axioms Erdos617.card_edges_ge_thirtySix_of_admissible_indepSetFree_three_card_eleven

#print axioms Erdos617.not_colorable_of_indepSetFree_of_mul_lt_card
#print axioms Erdos617.indepSetFree_six_not_colorable_five_fin26
#print axioms Erdos617.colorGraph_not_colorable_five_of_counterexample
#print axioms Erdos617.admissible_cliqueFree_six
#print axioms Erdos617.degree_eq_five_of_card_le_65_of_degree_ge_five
#print axioms Erdos617.exists_sparse_nonisolated_nonfiveColorable_colorGraph
#print axioms Erdos617.sparse_colorGraph_degree_eq_five_of_degree_ge_five
#print axioms Erdos617.exists_sparse_colorGraph_vertex_degree_le_four_of_special_brooks

#print axioms Erdos617.balancedC5Blowup_adj
#print axioms Erdos617.balancedC5MaxIndep_card
#print axioms Erdos617.balancedC5MaxIndep_index_check
#print axioms Erdos617.balancedC5MaxIndep_isIndepSet
#print axioms Erdos617.balancedC5MinCover_card
#print axioms Erdos617.balancedC5MinCover_index_check
#print axioms Erdos617.balancedC5MinCover_isVertexCover
#print axioms Erdos617.equivProdOfFiberCardTwo_fst
#print axioms Erdos617.isBipartiteWith_of_independent_partition
#print axioms Erdos617.labelOfUniqueFiveParts_mem
#print axioms Erdos617.labelOfUniqueFiveParts_eq_iff
#print axioms Erdos617.fin_five_degree_zero_formula
#print axioms Erdos617.fin_five_degree_one_formula
#print axioms Erdos617.fin_five_degree_two_formula
#print axioms Erdos617.fin_five_degree_three_formula
#print axioms Erdos617.fin_five_degree_four_formula
#print axioms Erdos617.bool_not_three_and_eq_true_iff
#print axioms Erdos617.bool_edge_condition_eq_true_iff
#print axioms Erdos617.finTwoToBool_boolToFinTwo
#print axioms Erdos617.five_edge_bits_degree_code_check
#print axioms Erdos617.five_edge_bits_degree_check
#print axioms Erdos617.five_subset_bits_code_check
#print axioms Erdos617.five_subset_bits_check
#print axioms Erdos617.six_cover_bits_code_check
#print axioms Erdos617.six_cover_bits_check
#print axioms Erdos617.sum_membership_bits_eq_card
#print axioms Erdos617.balancedC5Blowup_indepSetFree_five
#print axioms Erdos617.balancedC5Blowup_indepNum
#print axioms Erdos617.balancedC5Blowup_six_cover_iff
#print axioms Erdos617.six_le_card_of_balancedC5Blowup_vertexCover
#print axioms Erdos617.balancedC5Blowup_vertexCoverNum
#print axioms Erdos617.balancedC5MinCover_inter_card_check
#print axioms Erdos617.balancedC5Blowup_distinct_min_covers_inter_card_le_four
#print axioms Erdos617.five_edge_bits_degree_structure
#print axioms Erdos617.fin_five_exterior_degree_structure
#print axioms Erdos617.five_exterior_degree_structure
#print axioms Erdos617.compl_isBipartite_of_degree_eq_five_card_ten
#print axioms Erdos617.card_compl_edges_le_twenty_of_admissible_order_ten_nonbipartite
#print axioms Erdos617.compl_degree_eq_four_of_admissible_order_ten_nonbipartite_twenty_edges
#print axioms Erdos617.order_ten_exterior_degree_structure
#print axioms Erdos617.order_ten_exterior_cycle_degree_structure
#print axioms Erdos617.compl_iso_balancedC5Blowup_of_admissible_order_ten_equality
#print axioms Erdos617.compl_vertexCoverNum_eq_six_of_admissible_order_ten_equality
#print axioms Erdos617.compl_indepSetFree_five_of_admissible_order_ten_nineteen_edges
#print axioms Erdos617.degree_between_comm
#print axioms Erdos617.degree_between_add_compl_between_eq_card
#print axioms Erdos617.exists_bipartition_order_ten

#print axioms Erdos617.false_of_indepSetFree_four_of_pairwise_nonadj
#print axioms Erdos617.degree_add_degree_le_card_edges_add_one_of_adj
#print axioms Erdos617.false_of_bipartite_compl_exterior_degree_five_card_sixteen
#print axioms Erdos617.false_of_nonbipartite_compl_exterior_degree_five_card_sixteen
#print axioms Erdos617.card_edges_ge_fortyFive_of_admissible_indepSetFree_four_card_sixteen
#print axioms Erdos617.card_edges_ge_fifty_of_admissible_indepSetFree_four_card_seventeen
#print axioms Erdos617.false_of_admissible_indepSetFree_four_small_range

#print axioms Erdos617.card_induce_closedNeighborhood_eq_degree_add_internal
#print axioms Erdos617.card_edges_eq_exterior_add_degree_add_accounting
#print axioms Erdos617.compl_colorable_three_of_three_clique_cover
#print axioms Erdos617.neighborhood_isClique_of_bipartite_compl_exterior_order_ten
#print axioms Erdos617.compl_colorable_three_of_bipartite_compl_exterior_degree_four
#print axioms Erdos617.card_edges_le_twentyFive_of_admissible_order_ten_compl_bipartite
#print axioms Erdos617.exists_minimal_degree_four_of_admissible_indepSetFree_four_card_fifteen
#print axioms Erdos617.closedNeighborhood_isClique_of_internal_eq_choose
#print axioms Erdos617.orderFifteenThirtyFiveStructure_of_admissible
#print axioms Erdos617.orderFifteenThirtySixIsolatedStructure_of_exterior_twentySix
#print axioms Erdos617.false_of_orderFifteen_exterior_twentyFive_internal_five
#print axioms Erdos617.orderFifteenThirtySixOneCrossStructure_of_exterior_twentyFive
#print axioms Erdos617.orderFifteenThirtySixStructure_or_of_admissible
#print axioms Erdos617.card_between_compl_eq_zero_of_isIsolatedCliqueOn
#print axioms Erdos617.orderFifteenThirtySixStructures_incompatible
#print axioms Erdos617.orderFifteenThirtySixStructure_xor_of_admissible

#print axioms Erdos617.card_edges_ge_thirtyFive_of_admissible_indepSetFree_four_card_fifteen_not_colorable
#print axioms Erdos617.card_edges_ge_sixtyTwo_of_admissible_indepSetFree_five_card_twentyThree
#print axioms Erdos617.card_edges_ge_fiftyNine_of_admissible_indepSetFree_five_card_twentyTwo
#print axioms Erdos617.card_filter_adj_le_one_of_admissible_clique_five
#print axioms Erdos617.exists_three_five_clique_partition_of_compl_colorable_order_fifteen
#print axioms Erdos617.false_of_indepSetFree_five_of_pairwise_nonadj
#print axioms Erdos617.neighborhood_isClique_of_colorable_compl_exterior_degree_five_card_twentyOne
#print axioms Erdos617.false_of_colorable_compl_exterior_degree_five_card_twentyOne
#print axioms Erdos617.false_of_not_colorable_compl_exterior_degree_five_card_twentyOne
#print axioms Erdos617.card_edges_ge_fiftyFive_of_admissible_indepSetFree_five_card_twentyOne
#print axioms Erdos617.false_of_admissible_indepSetFree_five_small_range

#print axioms Erdos617.exists_minimal_colorGraph_degree_two_to_four_of_card_le_65
#print axioms Erdos617.colorGraph_card_eq_65_of_card_le_65_of_special_brooks
#print axioms Erdos617.all_colorGraph_card_eq_65_of_special_brooks
#print axioms Erdos617.degree_induce_finset_compl_eq_of_isIsolatedCliqueOn
#print axioms Erdos617.degree_induce_exterior_eq_of_isolatedClosedNeighborhood
#print axioms Erdos617.false_of_admissible_indepSetFree_six_card_twentySix_edges_sixtyFive_minDegree_two
#print axioms Erdos617.false_of_admissible_indepSetFree_six_card_twentySix_edges_sixtyFive_minDegree_three
#print axioms Erdos617.exists_minimal_colorGraph_degree_four_of_special_brooks
#print axioms Erdos617.colorGraph_residualStructure_of_special_brooks

#print axioms Erdos617.six_le_card_of_vertexCover_of_indepSetFree_five_card_ten
#print axioms Erdos617.six_le_cross_degree_add_of_nonadjacent_pair
#print axioms Erdos617.mem_crossNeighborFinset_iff
#print axioms Erdos617.card_crossNeighborFinset_eq_between_degree
#print axioms Erdos617.crossNeighbor_union_isVertexCover_of_nonadjacent_pair
#print axioms Erdos617.six_vertexCovers_eq_or_inter_card_le_four_of_iso_balancedC5Blowup
#print axioms Erdos617.false_of_canonical_order_ten_excess_one
#print axioms Erdos617.five_edge_small_degree_sum_code_check
#print axioms Erdos617.five_edge_small_degree_sum_check
#print axioms Erdos617.exists_adj_degree_add_le_five_of_card_five_edges_five
#print axioms Erdos617.false_of_admissible_indepSetFree_four_card_sixteen_edges_fortyFive_minDegree_five
#print axioms Erdos617.false_of_admissible_indepSetFree_five_card_twentyOne_edges_fiftyFive_degree_four
#print axioms Erdos617.five_le_degree_of_admissible_indepSetFree_five_card_twentyOne_edges_fiftyFive

#print axioms Erdos617.mem_residualCrossNeighborFinset_iff
#print axioms Erdos617.card_residualCrossNeighborFinset_le_between_degree
#print axioms Erdos617.residualCrossNeighbor_union_isVertexCover_with_avoider
#print axioms Erdos617.exists_mem_clique_five_avoiding_pair
#print axioms Erdos617.exists_mem_clique_five_avoiding_pair_and_ne
#print axioms Erdos617.exists_left_endpoint_of_card_between_eq_one
#print axioms Erdos617.six_le_card_of_vertexCover_of_iso_balancedC5Blowup
#print axioms Erdos617.false_of_canonical_residual_excess_one_of_edge_covers
#print axioms Erdos617.false_of_admissible_indepSetFree_five_card_twentyOne_edges_fiftyFive_minDegree_five_at
#print axioms Erdos617.false_of_admissible_indepSetFree_five_card_twentyOne_edges_fiftyFive_minDegree_five
#print axioms Erdos617.false_of_admissible_indepSetFree_five_card_twentyOne_edges_fiftyFive_minDegree_four
#print axioms Erdos617.false_of_r5ColorGraphResidualStructure
#print axioms Erdos617.no_r5_counterexample_of_special_brooks
#print axioms Erdos617.r5Upper_of_special_brooks
#print axioms Erdos617.problem617At_five_of_special_brooks
